# apstools.devices.ad_creator:
#   - name: blackfly_det
#     prefix: "usxFLY1:"
#     labels: ["camera", "area_detector"]
#     plugins:
#       - cam:
#           class: ophyd.PointGreyDetectorCam
#       - image:
#           class: ophyd.ImagePlugin

usaxs.devices.blackfly_module.MyPointGreyDetector:
- name: blackfly_det
  prefix: "usxFLY1:"
  labels: ["camera", "area_detector"]

usaxs.devices.blackfly_module.MyPointGreyDetector:
- name: blackfly_optical
  prefix: "usxFLY2:"
  labels: ["camera", "area_detector"]
