# Must be loaded _after_ separate file with amplifiers, scalers, etc.

usaxs.devices.amplifiers.DetectorAmplifierAutorangeDevice:
  - name: I0_controls
    nickname: I0
    scaler: scaler0
    det: I0

  - name: I00_controls
    nickname: I00
    scaler: scaler0
    det: I00

  # Nothing for I000

  - name: trd_controls
    nickname: "TRD"
    scaler: scaler0
    det: trd

  - name: upd_controls
    nickname: UPD
    scaler: scaler0
    det: upd
