# Guarneri-style device YAML configuration

# Objects only available at APS

apstools.devices.ApsMachineParametersDevice:
  - name: aps

# usaxs.devices.shutters.My12IdPssShutter: # TODO: make sure logic is implemented
