# # Guarneri-style device YAML configuration

apsbits.utils.sim_creator.predefined_device:
- {creator: ophyd.sim.motor, name: sim_motor}
- {creator: ophyd.sim.noisy_det, name: sim_det}

apstools.devices.SimulatedApsPssShutterWithStatus:
- name: shutter
  labels: ["shutters"]

apstools.devices.PlanarUndulator:
- name: undulator
  prefix: "S12ID:USID:"

usaxs.devices.autocollect.AutoCollectDataDevice:
- name: auto_collect
  prefix: "usxLAX:AutoCollection"

usaxs.devices.diagnostics.DiagnosticsParameters:
- name: diagnostics

usaxs.devices.general_terms.GeneralParameters: #TODO: look at this again
- name: terms

usaxs.devices.autosave.Autosave:
- name: lax_autosave
  prefix: "usxLAX:"

usaxs.devices.filters.FilterBank:
- name: Filter_AlTi
  prefix: "12idPyFilter:"
  bank: FL1


usaxs.devices.linkam.My_Linkam_T96_Device:
- name: linkam_tc1
  prefix: "usxLINKAM:tc1:"

usaxs.devices.monochromator.MyMonochromator:
- name: monochromator

apstools.synApps.swait.SwaitRecord:
- name: usaxs_q_calc
  prefix: usxLAX:USAXS:Q

apstools.synApps.swait.UserCalcsDevice:
- name: userCalcs_lax
  prefix: "usxLAX:"

ophyd.EpicsSignal: #TODO: Double check my work
- name: ar_start
  read_pv: usxLAX:USAXS:ARstart
  write_pv: usxLAX:USAXS:ARstart

ophyd.EpicsSignalRO:
- name: usaxs_CheckBeamStandard
  read_pv: usxLAX:blCalc:userCalc1
  auto_monitor: false

ophyd.EpicsMotor:
- name: LAXm1
  prefix: usxLAX:m58:c0:m1
  labels: ["LAXm1"]
- name: LAXm2
  prefix: usxLAX:m58:c0:m2
  labels: ["LAXm2"]
- name: LAXm3
  prefix: usxLAX:m58:c0:m3
  labels: ["LAXm3"]
- name: LAXm4
  prefix: usxLAX:m58:c0:m4
  labels: ["LAXm4"]
- name: LAXm5
  prefix: usxLAX:m58:c0:m5
  labels: ["LAXtcam"]
- name: LAXm6
  prefix: usxLAX:m58:c0:m6
  labels: ["LAXgsy"]
- name: LAXm7
  prefix: usxLAX:m58:c0:m7
  labels: ["LAXgsx"]
- name: LAXm8
  prefix: usxLAX:m58:c0:m8
  labels: ["LAXm8"]
- name: waxsx
  prefix: usxAERO:m3
  labels: ["wasxs", "motor"]
- name: waxs2x
  prefix: usxAERO:m7
  labels: ["waxs2x", "motor"]

usaxs.devices.ptc10_controller.USAXS_PTC10: #TODO: Go into source and fix
- name: ptc10
  prefix: "usxTEMP:tc1:"

usaxs.devices.sample_data.SampleDataDevice:
- name: sample_data_device

usaxs.devices.sample_rotator.SampleRotator:
- name: pi_c867
  prefix: usxPI:c867:c0:m1

apstools.devices.Struck3820:
- name: struck
  prefix: "usxLAX:3820:"

# usaxs.devices.slits.GSlitDevice: #TODO: Rethink how this device works
# - name: guard_slit
#   prefix: ""

# usaxs.devices.slits.UsaxsSlitDevice:
# - name: usaxs_slit
#   prefix: ""

usaxs.devices.trajectories.Trajectories:
- name: "flyscan_trajectories"

usaxs.devices.user_data.UserDataDevice:
- name: user_device

usaxs.devices.white_beam_ready_calc.WhiteBeamReadyCalc:
- name: white_beam_ready
  prefix: "usxLAX:userCalc9"

usaxs.devices.stages.GuardSlitsStageDevice:
- name: gslit_stage

usaxs.devices.stages.UsaxsSampleStageDevice:
- name: s_stage

usaxs.devices.stages.UsaxsDetectorStageDevice:
- name: d_stage

usaxs.devices.stages.UsaxsCollimatorStageDevice:
- name: m_stage

usaxs.devices.stages.UsaxsAnalyzerStageDevice:
- name: a_stage

usaxs.devices.stages.SaxsDetectorStageDevice:
- name: saxs_stage


# # apstools.devices.ad_creator:
# #   - name: adsimdet
# #     prefix: "ad:"
# #     labels: ["area_detector", "detectors"]
# #     plugins:
# #       - cam:
# #           class: apstools.devices.SimDetectorCam_V34
# #       - image
# #       - pva
# #       - hdf1:
# #           class: apstools.devices.AD_EpicsFileNameHDF5Plugin
# #           read_path_template: "/path/to/bluesky/tmp/"
# #           write_path_template: "/path/to/ioc/tmp/"
# #       - roi1
# #       - stats1
