# Guarneri-style device YAML configuration

apsbits.utils.sim_creator.predefined_device:
- {creator: ophyd.sim.motor, name: sim_motor}
- {creator: ophyd.sim.noisy_det, name: sim_det}

apstools.devices.SimulatedApsPssShutterWithStatus:
- name: shutter
  labels: ["shutters"]

apstools.devices.ApsMachineParametersDevice:
- name: aps

apstools.devices.PlanarUndulator:
- name: undulator
  prefix: "S12ID:USID:" 

usaxs.devices.autosave.Autosave:
- name: lax_autosave
  prefix: "usxLAX:"

usaxs.devices.filters.FilterBank:
- name: Filter_AlTi
  prefix: "12idPyFilter:"
  bank: FL1

usaxs.devices.ioc_stats.IocInfoDevice:
- name: gp_stats
  prefix: "gp:"

apstools.synApps.swait.SwaitRecord:
- name: usaxs_q_calc
  prefix: usxLAX:USAXS:Q

apstools.synApps.swait.UserCalcsDevice:
- name : userCalcs_lax
  prefix: "usxLAX:"

ophyd.EpicsSignal: #TODO: Double check my work
- name: ar_start
  read_pv: usxLAX:USAXS:ARstart

ophyd.EpicsSignalRO:
- name: usaxs_CheckBeamStandard
  read_pv: usxLAX:blCalc:userCalc1
  auto_monitor: False

ophyd.EpicsMotor:
- {name: LAXm1, prefix: usxLAX:m58:c0:m1, labels: ["LAXm1"]}
- {name: LAXm2, prefix: usxLAX:m58:c0:m2, labels: ["LAXm2"]}
- {name: LAXm3, prefix: usxLAX:m58:c0:m3, labels: ["LAXm3"]}
- {name: LAXm4, prefix: usxLAX:m58:c0:m4, labels: ["LAXm4"]}
- {name: LAXm5, prefix: usxLAX:m58:c0:m5, labels: ["LAXtcam"]}
- {name: LAXm6, prefix: usxLAX:m58:c0:m6, labels: ["LAXgsy"]}
- {name: LAXm7, prefix: usxLAX:m58:c0:m7, labels: ["LAXgsx"]}
- {name: LAXm8, prefix: usxLAX:m58:c0:m8, labels: ["LAXm8"]}

usaxs.devices.ptc10_controller.USAXS_PTC10:
- name: ptc10
  prefix: "usxTEMP:tc1:"

usaxs.devices.sample_data.SampleDataDevice:
- name: sample_data_device

usaxs.devices.sample_rotator.SampleRotator: 
- name: pi_c867
  prefix: usxPI:c867:c0:m1

# usaxs.devices.shutters.My12IdPssShutter: # TODO: make sure this is correct

apstools.devices.Struck3820:
- name: struck
  prefix: "usxLAX:3820:"

usaxs.devices.slits.GSlitDevice:
- name: guard_slit
  prefix: ""

usaxs.devices.slits.UsaxsSlitDevice:
- name: usaxs_slit
  prefix: ""

usaxs.devices.trajectories.TrajectoryDevice:
- name: "flyscan_trajectories"

usaxs.devices.user_devices.UserDevice:
- name: user_device

usaxs.devices.white_beam.WhiteBeamReadyCalc:
- name: white_beam_ready
  prefix: "usxLAX:userCalc9"


# ophyd.Signal:
# - name: test
#   value: 50.7
# - name: t2
#   value: 2

# apstools.synApps.Optics2Slit2D_HV:
# - name: slit1
#   prefix: ioc:Slit1
#   labels: ["slits"]

# hkl.SimulatedE4CV:
# - name: sim4c
#   prefix: ""
#   labels: ["diffractometer"]

# ophyd.scaler.ScalerCH:
# - name: scaler1
#   prefix: vme:scaler1
#   labels: ["scalers", "detectors"]



# apstools.devices.ad_creator:
#   - name: adsimdet
#     prefix: "ad:"
#     labels: ["area_detector", "detectors"]
#     plugins:
#       - cam:
#           class: apstools.devices.SimDetectorCam_V34
#       - image
#       - pva
#       - hdf1:
#           class: apstools.devices.AD_EpicsFileNameHDF5Plugin
#           read_path_template: "/path/to/bluesky/tmp/"
#           write_path_template: "/path/to/ioc/tmp/"
#       - roi1
#       - stats1
