# Guarneri-style device YAML configuration

# Objects only available at APS

apstools.devices.ApsMachineParametersDevice:
  - name: aps
    labels:
    - baseline

# usaxs.devices.shutters.My12IdPssShutter: # TODO: make sure logic is implemented

apstools.devices.PlanarUndulator:
- name: undulator
  prefix: "S12ID:USID:"
  labels: 
  - baseline
