usaxs.devices.shutters.My12IdPssShutter:
- name: FE_shutter
  state_pv: "PA:12ID:STA_A_FES_OPEN_PL"
  labels: ["shutters"]

apstools.devices.ApsPssShutterWithStatus:
- name: mono_shutter
  state_pv: "PA:12ID:STA_C_SCS_OPEN_PL"
  open_pv: "12ida2:rShtrC:Open"
  close_pv: "12ida2:rShtrC:Close"

apstools.devices.ApsPssShutter:
- name: usaxs_shutter
  open_pv: 12idc:uniblitz:shutter:open
  close_pv: 12idc:uniblitz:shutter:close

ophyd.signal.EpicsSignal:
- name: a_shutter_autoopen
  prefix: "12ida2:AShtr:Enable"
